/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'availabilityDays' : IDL.Vec(IDL.Text),
  'qualification' : IDL.Text,
});
export const DoctorId = IDL.Nat;
export const HealthPackage = IDL.Record({
  'name' : IDL.Text,
  'includedTests' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const PackageId = IDL.Nat;
export const Service = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'serviceType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'bookingTime' : IDL.Int,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
});
export const AppointmentId = IDL.Nat;
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctor' : IDL.Func([Doctor], [DoctorId], []),
  'addHealthPackage' : IDL.Func([HealthPackage], [PackageId], []),
  'addService' : IDL.Func([Service], [ServiceId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Appointment], [AppointmentId], []),
  'deleteAppointment' : IDL.Func([AppointmentId], [], []),
  'deleteDoctor' : IDL.Func([DoctorId], [], []),
  'deleteHealthPackage' : IDL.Func([PackageId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateDoctor' : IDL.Func([DoctorId, Doctor], [], []),
  'updateHealthPackage' : IDL.Func([PackageId, HealthPackage], [], []),
  'updateService' : IDL.Func([ServiceId, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'availabilityDays' : IDL.Vec(IDL.Text),
    'qualification' : IDL.Text,
  });
  const DoctorId = IDL.Nat;
  const HealthPackage = IDL.Record({
    'name' : IDL.Text,
    'includedTests' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const PackageId = IDL.Nat;
  const Service = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'serviceType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'bookingTime' : IDL.Int,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AppointmentId = IDL.Nat;
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctor' : IDL.Func([Doctor], [DoctorId], []),
    'addHealthPackage' : IDL.Func([HealthPackage], [PackageId], []),
    'addService' : IDL.Func([Service], [ServiceId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Appointment], [AppointmentId], []),
    'deleteAppointment' : IDL.Func([AppointmentId], [], []),
    'deleteDoctor' : IDL.Func([DoctorId], [], []),
    'deleteHealthPackage' : IDL.Func([PackageId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateDoctor' : IDL.Func([DoctorId, Doctor], [], []),
    'updateHealthPackage' : IDL.Func([PackageId, HealthPackage], [], []),
    'updateService' : IDL.Func([ServiceId, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };