/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'serviceType' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'bookingTime' : bigint,
  'patientName' : string,
  'phone' : string,
}
export type AppointmentId = bigint;
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Doctor {
  'name' : string,
  'specialty' : string,
  'availabilityDays' : Array<string>,
  'qualification' : string,
}
export type DoctorId = bigint;
export interface HealthPackage {
  'name' : string,
  'includedTests' : Array<string>,
  'price' : bigint,
}
export type PackageId = bigint;
export interface Service {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type ServiceId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctor' : ActorMethod<[Doctor], DoctorId>,
  'addHealthPackage' : ActorMethod<[HealthPackage], PackageId>,
  'addService' : ActorMethod<[Service], ServiceId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], AppointmentId>,
  'deleteAppointment' : ActorMethod<[AppointmentId], undefined>,
  'deleteDoctor' : ActorMethod<[DoctorId], undefined>,
  'deleteHealthPackage' : ActorMethod<[PackageId], undefined>,
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateDoctor' : ActorMethod<[DoctorId, Doctor], undefined>,
  'updateHealthPackage' : ActorMethod<[PackageId, HealthPackage], undefined>,
  'updateService' : ActorMethod<[ServiceId, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];